#!/usr/bin/python
def integer(n) :
    if (n <= 0) :
        print"Not Valid"
    for i in range(1,n+1) :
        if (n % i == 0) :
            print i



print"all divisors of 25: ", integer(25)
print"all divisors of -25: ", integer(-25)
print"all divisors of 0: ", integer(0)
print"all divisors of 5: ", integer(5)