#!/usr/bin/python
def amicable(n,m) :
    if (n <= 0 or m <= 0) :
        print "Not Valid"
        return
    temp1 = 0
    temp2 = 0
    for i in range (1,n) :
        if (n % i == 0) :
            temp1 = temp1 + i
    for j in range (1,m) :
        if (m % j == 0) :
            temp2 = temp2 + j
    if (temp1 == m and temp2 == n) :
        print "numbers are Amicable"
    else :
        print "numbers are not Amicable"


amicable(220,284)
amicable(22,28)
amicable(0,0)
amicable(220,-284)
amicable(1184,1210)

