#!/usr/bin/python
def palindrome(n) :
    if (n <= 0) : print "Not Valid"
    prod = n
    a = 0
    rev = 0
    while (n > 0) :
        a = n % 10
        rev = (rev * 10) + a
        n = n / 10
    if (prod == rev) :
        print "number is palindrome"
    else :
        print "number is not palindrome"




palindrome(121)
palindrome(123)
palindrome(-121)
palindrome(0)
palindrome(123454321)
