#!/usr/bin/python
def numbers(list) :

    even = []
    odd = []

    for i in list :
        if (i % 2 == 0) :
            even.append(i)
        else :
            odd.append(i)
    print "even numbers are: ", even
    print "odd numbers are: " , odd




numbers([2,5,7,9,8,10])





