#!/usr/bin/python
def gcd(n,m) :
    prod = 1
    if (n == 0 or m == 0) :
        print "GCD is:  0"
        return
    if (n == m) :
        print "GCD is: ", n
        return
    if (n > m) :
        s = m
    if (n < m) :
        s = n
    for i in range (1, s + 1) :
        if (n % i == 0 and m % i == 0):
            prod = prod * i
            n = n / i
            m = m / i
    print "GCD is: ", prod

gcd(4,6)
gcd(0,7)
gcd(4,4)
gcd(8,16)
gcd(16,8)