#!/usr/bin/python
from sys import maxint
def biggest(list):
    num = -maxint
    for i in list :
        if (num < i) :
            num = i
    return num

val = biggest([5,6])
print"biggest number in list is: ", val

val = biggest([53,4,7])
print"biggest number in list is: ", val

val = biggest([62,675,8888])
print"biggest number in list is: ", val

val = biggest([-5,-86])
print"biggest number in list is: ", val

val = biggest([0,0])
print"biggest number in list is: ", val

val = biggest([-5,-5])
print"biggest number in list is: ", val

val = biggest([1,1])
print"biggest number in list is: ", val
