#!/usr/bin/python
def lcm(n,m) :
    prod = 1
    if (n == m) :
        print "LCM is: ", n
        return
    if (n > m) :
        s = m
    elif (n < m) :
        s = n

    for i in range (1, s + 1) :
        if (n % i == 0 and m % i == 0) :
            prod = prod * i
            n = n / i
            m = m / i
    prod = prod * n * m
    print "LCM is: ", prod


lcm(4,6)
lcm(0,7)
lcm(4,4)
lcm(8,16)
lcm(16,8)