#!/usr/bin/python
for n in range(1, 101):
    if n == 1:
        print "1 is neither prime nor composite "
        continue
    if n == 2:
        print "2 is prime number"
        continue
    prime = True
    for i in range (2,n) :
        if (n % i == 0) :
            prime = False
            break
    if prime :
        print "prime numbers are: ", n
