#!/usr/bin/python
def strong(n) :
    p = 0
    if (n <= 0) :
        print "not valid"
    if (n > 0) :
        temp = n
        while (temp) :
            k = temp % 10
            m = 1
            for i in range(1,k+1) :
                m = m * i
            p = p + m
            temp = temp / 10
        if (p == n) :
            print"It's strong number"
        else :
            print "It's not strong number"



print "is 145 strong number: ", strong(145)
print "is 0 strong number: ", strong(0)
print "is 14 strong number: ", strong(14)