#!/usr/bin/python
def cosine(x,n) :
    pie = float(22 / 7)
    y = float((x * pie) / 180)
    cosx = 0
    for i in range(0, n + 1):
        f = 1
        for j in range(1, 2 * i + 1):
            f = f * j
        cosx = cosx + float((((-1) ** i) * (y ** (2. * i ))) / f)
    print cosx
    return


cosine(0,5)
cosine(60,3)