#!/usr/bin/python
class Node :
    def __init__(self, data):
        self.data = data
        self.next = None


class linkedlist :
    def __init__(self):
        self.head = None

    def push(self, new_data):
        new_node = Node(new_data)
        new_node.next = self.head
        self.head = new_node


    def display(self):
        temp = self.head
        while temp:
          print temp.data
          temp = temp.next

    def find_loop(self):
        fast = self.head
        slow = self.head
        while (slow and fast and fast.next):
            slow = slow.next
            fast = fast.next.next
            if slow == fast:
                print "Loop foud"
                return





llist = linkedlist()
llist.push(10)
llist.push(20)
llist.push(30)
llist.push(40)
llist.push(50)
llist.display()
llist.head.next.next.next.next = llist.head
llist.find_loop()


