#!/usr/bin/python
class node :
    def __init__(self, data):
        self.data = data
        self.next = None

class stack :
    def __init__(self):
        self.head = None

    def push(self, data):
        if self.head == None:
            self.head = node(data)
        else :
            new_node = node(data)
            new_node.next = self.head
            self.head = new_node

    def pop(self):
        if self.head == None:
            print "List is empty"
        else:
            temp = self.head.data
            self.head = self.head.next
            return temp



s = stack()
s.push(10)
s.push(20)
s.pop()
s.push(30)







