#!/usr/bin/python
class node :
    def __init__(self, data):
        self.data = data
        self.next = None

class find :
    def __init__(self):
        self.head = None

    def push(self, new_data):
        new_node = node(new_data)
        new_node.next = self.head
        self.head = new_node

    def Nth_node(self, index):
        current = self.head
        count = 0
        while (current):
            if (count == index):
              return current.data
            count = count + 1
            current = current.next


f = find()
f.push(2)
f.push(33)
f.push(55)
f.push(7)
f.push(82)
f.push(90)
print"element in 4th node is: ", f.Nth_node(4)




