#!/usr/bin/python

class Node:
    def __init__(self,data):
       self.data = data
       self.left = None
       self.right = None


    def insert(self, data):
        if data < self.data:
            if self.left is None:
                self.left = Node(data)
            else:
                self.left.insert(data)
        else:
            if self.right is None:
                self.right = Node(data)
            else:
                self.right.insert(data)


def minValue (node):
    current = node
    while (current.left is not None):
        current = current.left

    return current.data


root = Node(4)
root.insert(2)
root.insert(1)
root.insert(3)
root.insert(6)
root.insert(5)

print "\nMinimum value in BST is %d" % (minValue(root))



