#!/usr/bin/python

class Node(object):
    def __init__(self, data):
        self.data = data
        self.left = None
        self.right = None

    def halfcount(root):
        if root is None:
            return 0

        queue = []
        queue.append(root)
        count = 0
        while (len(queue) > 0):
            key = queue.pop(0)
            if (key.left is not None and key.right is None) or (key.right is not None and key.left is None);
                count = count +1

            if key.left is not None:
                queue.append(key.left)

            if key.right is not None:
                queue.append(key.right)

        return count


root = Node(2)
root.left = Node(7)
root.right = Node(5)
root.left.right = Node(6)
root.left.right.left = Node(1)
root.left.right.right = Node(11)
root.right.right = Node(9)
root.right.right.left = Node(4)

print "%d", halfcount(root)





